### PR TITLE
Update redirects in Readme

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by sergeyklay** [comment]
https://travis-ci.org/sergeyklay/awesome-phalcon/builds/91045453

**Comment by ReadmeCritic** [comment]
@sergeyklay ✅

**Comment by sergeyklay** [comment]
Thanks

**Comment by ReadmeCritic** [comment]
:smile:

**Pull request merged**
