### PR TITLE
Fix gettext-volt link and improve gettext-volt explanation.

### PR DESCRIPTION
**Pull request by dschissler**

### CODE REVIEW

**Review by sergeyklay — CHANGES_REQUESTED** [review]
```
curl -I https://github.com/perchlayer/xgettext-volt
HTTP/1.1 404 Not Found
```

**Review by sergeyklay — CHANGES_REQUESTED** [review]
Could you please reorder list alphabetically

**Comment by dschissler** [comment]
On initial thought it sounded good but then I realized that if I made this change that `xgettext-template` and `gettext-volt` won't be next to each other.

Actually `gettext-volt` doesn't really need to be its own entry since it plugs into (the umbrella project) `xgettext-template`.  Perhaps I could delete `gettext-volt` and to describe `xgettext-template` in terms of what it specifically does for Volt.  So I would combine the two lines with some rewording.

Sound good?

**Comment by sergeyklay** [comment]
Sounds good to me

**Comment by sergeyklay** [comment]
@dschissler

**Review by sergeyklay — APPROVED** [review]

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
